# Generated by Django 3.2.2 on 2021-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diseño_iddiseño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='idDiseño',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ID del diseño'),
        ),
    ]
