# Generated by Django 3.2.2 on 2021-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_diseño_iddiseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuador',
            name='edadTatuador',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='emailTatuador',
            field=models.CharField(max_length=20, null=True, verbose_name='Email del tatuador'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='catalogo_tatuador'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='numTatuador',
            field=models.IntegerField(null=True),
        ),
    ]
