# Generated by Django 3.2.2 on 2021-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210529_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseño',
            old_name='idDiseño',
            new_name='idDiseno',
        ),
        migrations.AddField(
            model_name='diseño',
            name='imgdis',
            field=models.ImageField(null=True, upload_to='catalogo_diseño'),
        ),
    ]
