# Generated by Django 3.2.2 on 2021-06-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210531_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('idDiseno', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ID del diseño')),
                ('nombreDiseno', models.CharField(max_length=20, verbose_name='Nombre del Diseño')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria del diseño')),
                ('imgdiseno', models.ImageField(null=True, upload_to='catalogo_diseno')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tatuador')),
            ],
        ),
        migrations.DeleteModel(
            name='Diseño',
        ),
    ]
