# Generated by Django 3.2.2 on 2021-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210531_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreuser', models.CharField(max_length=30, verbose_name='nombre del user')),
                ('apellidouser', models.CharField(max_length=30, verbose_name='apellido del user')),
                ('emailuser', models.CharField(max_length=30, verbose_name='email del user')),
                ('contrauser', models.CharField(max_length=30, verbose_name='contraseña del user')),
            ],
        ),
    ]
